### ISSUE TITLE
SMSIR_PANEL_ROUTES

### ISSUE THREAD

**Issue by Tahernejad** [IPeCompany/SmsPanelV2.Laravel#3]
Hi,
I want disable routes.
I added "SMSIR_PANEL_ROUTES=false" to .env but routes enabled yet,
I run "php artisan vendor:publish --provider Cryptommer\Smsir\SmsirServiceProvider" but isn't copied smsir.php in config folder.
Please help me,
Thanks

**Comment by cryptommer** [comment]
Hi,
Please send laravel version and error log for publishing provider 
Thank You

**Comment by Tahernejad** [comment]
Hi,

`
Laravel Framework 9.45.1
`

`
root@ecdc8de523a8:/var/www/laravel# php artisan vendor:publish --provider Cryptommer\Smsir\SmsirServiceProvider

   INFO  No publishable resources for tag [].

root@ecdc8de523a8:/var/www/laravel#
`

**Comment by cryptommer** [comment]
use this line 
php artisan vendor:publish --provider="Cryptommer\Smsir\SmsirServiceProvider"

**Comment by Tahernejad** [comment]
Thanks,
vendor publish successfully.
`
I added "SMSIR_PANEL_ROUTES=false" to .env but routes enabled yet,
`
problem not solved.

**Comment by bahramsadin** [comment]
#4

**Comment by Tahernejad** [comment]
@bahramsadin  Thank you
