### ISSUE TITLE
مشکل در ارسال پیامک گروهی

### ISSUE THREAD

**Issue by ErfKS** [IPeCompany/SmsPanelV2.Laravel#6]
سلام، من سعی کردم به کمک کد زیر، به صورت گروهی پیام ارسال کنم:

```
use Cryptommer\Smsir\Classes\Smsir;
$config = config('smsir');
$smsir = new Smsir($config['line-number'], $config['api-key']);
$send = $smsir->Send();
$send->Bulk('this is for test', ['0912xxxxxxx']);
```
در این حالت بالا، بجای `0912xxxxxxx` شماره واقعی که قرار میدم، بهم این خطا رو برمیگردونه:
```
{"status":101,"message":"شماره خط نامعتبر میباشد","data":null}
```
این درحالیست که من میتونم با استفاده از `$send->Verify()` بر اساس الگوی تعریف شده، به همین شماره sms ارسال میشه.

**Comment by cryptommer** [comment]
سلام
شماره موبایل درست است شماره خطی که باهاش دارین اس ام اس ارسال می کنین اشتباه است
line number را درست وارد نکرده اید
